# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-08 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhsstaffprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='nhsstaffprofile',
            name='nhs_email',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhsstaffprofile',
            name='nhs_profile_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
