# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-19 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
