# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-19 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171219_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='short_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
