# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-08 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171130_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
