# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-07 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_userproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='user',
        ),
        migrations.AddField(
            model_name='usertask',
            name='user_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.UserProject'),
            preserve_default=False,
        ),
    ]
