# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-16 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_name', models.CharField(max_length=255, null=True)),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture_taken_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
