# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-19 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('taken_on', models.DateTimeField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('location_name', models.CharField(max_length=255, null=True)),
                ('file_location', models.CharField(max_length=1000, null=True)),
                ('slug', models.SlugField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture_taken_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_tablespace': 'pg_default',
            },
        ),
    ]
