# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-23 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
